version: '3.8'

services:
  db:
    build:
      context: ./docker/database
    container_name: home_center_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: home_center
      MYSQL_USER: root
      MYSQL_PASSWORD: password

    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql
    networks:
      - symfony

  home_center:
    build:
      context: ./docker/apache
    container_name: home_center_symfony
    depends_on:
      - db
    volumes:
      - .:/var/www/home_center/
    ports:
      - 8000:80
    restart: always
    
    networks:
      - symfony

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: home_center_phpmyadmin
    links:
      - db
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_HOST: home_center_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - symfony

networks:
  symfony: